---
services:
  heskdb:
    image: mariadb
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      TZ: Asia/Shanghai
      MARIADB_ROOT_PASSWORD: abc123..
      MARIADB_DATABASE: hesk
      MARIADB_USER: hesk
      # Please change the password before deploying.
      MARIADB_PASSWORD: hesk
    
  heskweb:
    depends_on:
      - heskdb
    image: solyhe84/hesk
    volumes:
        - ./www:/srv  #Hesk文件目录可映射到寄主机
        - ./log:/var/log/apache2   #日志文件
    ports:
      - "8880:80"
    environment:
      - TZ=Asia/Shanghai
    restart: always
